### ISSUE TITLE
`README.md`에 명시한 사이트가 이상한 주소로 리다이렉션되는 문제

### ISSUE THREAD

**Issue by Daeho-Son** [NoEarthNoUs/SaveEarth#55]
@hwana @bohyunkang @boyeon555 

문제가 되는 주소입니다: `http://saveearth.shop/`

토토, 판다라이브, 성인 사이트 등 이상한 주소로 리다이렉션 되고 있습니다.
도메인이 만료 됐다면 `README.md`에서 지우셔야할 거 같습니다..!

**Comment by hwana** [comment]
@Daeho-Son 삭제 진행하였습니다. 알려주셔서 감사합니다!
